Update maven-publish.yml

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -41,7 +41,13 @@ jobs:
       run: mvn clean verify sonar:sonar -Dsonar.projectKey=chinnidhi_hello-world-war -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.organization=chinnidhi -Dsonar.branch.name=master
 
     # Step 6: Wait for the Quality Gate to be successful
-    - name: Check Quality Gate status
-      uses: sonarsource/sonarcloud-github-action@v1
-      env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+    - name: Wait for SonarCloud Quality Gate and Fail on Failure
+      run: |
+          response=$(curl -s -X GET -u "${{ secrets.SONAR_TOKEN }}": \
+            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=chinnidhi_hello-world-war")
+          status=$(echo $response | jq -r .projectStatus.status)
+          echo "Quality Gate status: $status"
+          if [ "$status" != "OK" ]; then
+            echo "Quality Gate failed. Exiting."
+            exit 1
+          fi
